### ISSUE TITLE
More BoM details

### ISSUE THREAD

**Issue by rwb27** [openUC2/UC2_openSIM#2]
Hello,
  I'm hoping to build one of these with a masters student this semester and am ordering the parts.  From the BoM on the readme page, I have currently ordered/obtained:

From Farnell/OneCall:
*  DMD |  Evaluierungsmodul (EVM) DLP® LightCrafter™ Display 2000 
* Raspberry Pi and accessories

I will order/have:

From ThorLabs:
* 2x Achromatic 1inch Lens, f=50mmmm
* 4x 8 inch cage rod for 30mm system
* 1" silver mirror
From RS:
* Micrometre for z-stage 

**Questions**:
* Tube-lens (Lens, f=180mm,  10 €, [PGI-Versand](https://www.pgi-versand.de/?id=47&mode=artdet&artnr=564.OA.64) ) what is the diameter, and is it an achromat?
* Dichroics: what size is needed, and is it just the standard excitation/emission/45 degree set for whatever fluorophore we're using
* iPhone lens: do you know what focal length I'm looking for, roughly?
* 25mm lens for telescope: is this an achromat, and what diameter does it need to be? 
* Related question: what's the target beam size on the DMD? I guess that sets the ratio of lenses in the telescope?

**Comment by beniroquai** [comment]
Hey Richard, 

thanks for reaching out! There have definitely been some updates here and there. The [assembly-guide](https://github.com/openUC2/UC2_openSIM/blob/main/Readme_SIM_alignment_tutorial.md) seems to be a bit more up to date. @ranranking, would you mind having a look at the [README](https://github.com/openUC2/UC2_openSIM/blob/main/REAMDE.md) and check if this is still ok? The renderings seem to be a bit old. 

The most important things you would need to get in order to get some SIM pattern in your sample plane are:

*Talking only about the openSIM module:*
[!](https://github.com/openUC2/UC2_openSIM/raw/main/IMAGES/OpticalPath.jpg)

* a laser, which wavelength? (532nm usually has great mode profile, 635nm usually works nice with a large variety of bright fluorophores => good for raspi cam); Beam-Diamter ~4mm 
* the proector (that's the DMD you mentioned)
* a 4f' system created by the 2 50mm achromats 
* the Fourier mask (wire + lead drop) + 3 magnets and ferromagentic plate 
* the rods for stabilization + thorlabs cage plates 
* 2 thorlabs cage plates for the 4f system + Fouriermask
* the magnets and screws for the UC2 system 
* some M3 cylindrical head screws
* a set of 4 springs for aligning the DMD
* some lenses (including the iphone lens) to form the beam expander (secondary lens has to be chosen - beam expander module has to be updated accordingly; We widened the beam quite a lot to have less fast-axis problems
* 


I think we need to put that into the new Readme.



**Q/A:**

`Tube-lens (Lens, f=180mm, 10 €, PGI-Versand ) what is the diameter, and is it an achromat?`
That'S a glassblock of 50mm diameter; It'S cheap and works well :-) 

`Dichroics: what size is needed, and is it just the standard excitation/emission/45 degree set for whatever fluorophore we're using`
Filters: 25mm, Dichroic 26*34 (@ranranking ?) - I think Comar does not sell the IY740 anymore.. are you aware of any alternative sources @rwb27 ? 

`iPhone lens: do you know what focal length I'm looking for, roughly?`
I think the iphone 4/5 has f'=4.2mm and NA=.21

`25mm lens for telescope: is this an achromat, and what diameter does it need to be?`
I remember that we had to change this due to space limitations. Alternative was: Remove the colimating lens of the laser and place the lens (not achromat though) at the focal lenght's distance away from the diode to illuminate the DMD. 

`Related question: what's the target beam size on the DMD? I guess that sets the ratio of lenses in the telescope?`
~20mm to fully overshine the aperture and have a ~homogenous illumination.. The red laser was quite light-sheet-ish ;-)

**Comment by beniroquai** [comment]
One more add regarding the cellphone lenses. Most likely you know [this paper](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0095330) already?

**Comment by rwb27** [comment]
Great, thanks.  I hadn't seen that paper but it does a nice job on resolution, field of view, and field flatness - I like it!

I think I'll prioritise ease over cheapness and use a ThorLabs LA1399 for the tube lens, hopefully it's close enough.  

I'll check what dichroics I have, and probably order some from comar or thorlabs in due course.  I don't know any easy alternatives to Comar or ThorLabs, would love to find them!

I'm not sure you actually specified the **diameter of the 25mm lens** - I'll assume probably it has to be quite big, like 25mm diameter, if we're expanding the beam to fill the DMD, though perhaps that bit is (a) easy to change and (b) depends on the laser...

**Comment by ranranking** [comment]
Hi, there are some open questions to me. 

First of all, i will try to polish the readme and update all the information to the current stage.

Dichroic: We used 2 different dichroics, 740IY and FF660-DI02. If you want to use ~638 laser as excitation, the FF660-DI02 is a nice choice. The dichroic holder is aimed for standard beamsplitter set, 25x36mm dichroics and dia 25mm ex/em filter.

Beam size: Since the active area of the DMD2000 is 4.8x2.7mm, the laser beam was expanded to roughly 15mm and try to make the DMD area covered by the fast axis region.

**Comment by rwb27** [comment]
thanks @beniroquai and @ranranking that's helpful.  I've just been pricing up lasers - I will probably get some from Roithner, and I might get 50mW at 450nm (for GFP type stuff) and 100mW at 532nm.  Do you think that might be enough, or is the 300mW you reference really required?

**Comment by beniroquai** [comment]
I think this really depends on the QE of your fluorophore and the camera
used. We used some old SiR Rhodamine to label the Cells actin network.
Something was a bit odd with the buffer I assume since it was bleaching
like crazy - or the SiR was just old. GFP will be a lot dimmer I would
assume...but depends on the sample preparation of course. Synthetic dyes
always work better. You could try a GFP-booster with an AF647 dye?
 You will lose a lot of light at the DMD - especially if you want to have
multiple wavelengths and do not consider the blazed (532, 450 nm would need
to have a very fancy setup; or you have it separated of course)
@ranranking <https://github.com/ranranking> did something towards
multicolour SIM using DMDs. Not trivial at all.
Roithner is a good source. However, pricy. Laserlands.net is accepted by
our institute moreless. They have "good" quality lasers and deliver fast.

What'S the camera you want to use?

>

**Comment by rwb27** [comment]
Ah, when I said GFP type stuff I should have said fluorescein-type stuff, at least in the first instance I just want to image easy test samples to prove it works, so a nice bright dye is the right answer.  I am often guilty of interchanging fluorescein and GFP because they often use the same filters :$  I'm not proposing to make it nicely multicolour, just hedging my bets against which laser we'll eventually choose!  That said, if I've understood correctly you're basically imaging the DMD into the sample - so surely that should be OK across the visible spectrum?

**Comment by beniroquai** [comment]
Basically yes. Though you have the Fourier filter in the DMD-module. 
In terms of beam quality I'd go for the frequency doubled 532nm laser. They have nicer "single-mode" behaviour/gaussian profile.For the DMD module however, we would need to slightly correct the angle. If your student can operate Inventor that's no problem! If he cant, we can help! :-)
The incident angle need to match.
