### ISSUE TITLE
How to connect Raspberry Pi and DMD

### ISSUE THREAD

**Issue by rwb27** [openUC2/UC2_openSIM#3]
We've got the PCB to connect the Pi and the DMD board, and are currently waiting on the connectors.  However, the [photo](https://github.com/openUC2/UC2_openSIM/blob/main/IMAGES/DMDMontage.jpg) shows several jumper leads still used: we think the orange wire is connecting a pin next to the DMD power connector to the adjacent header, but what are the yellow wires doing?

**Comment by beniroquai** [comment]
Hey! Good point! If I remember correctly, the photo you see is the first version I designed that had some false connections. So I had a fun time to find them (based on [this blog post](http://frederickvandenbosch.be/?p=2948)). In the end I updated the eagle project with (hopefully) the correct connections. The version that I uploaded should be correct. We also have some boards here that we could send over (including connectors). We wanted to perform a SIM workshop in London actually - COVID came; did not happen ;-) ..

**Comment by rwb27** [comment]
Super - we'll hopefully confirm later this week whether the PCB from the repository works!

**Comment by beniroquai** [comment]
Great. Shame on me if it doesn't work.

**Comment by rwb27** [comment]
Thanks.  We’ve not yet tried to show an image, but we are struggling to get the DMD chip in the right place because the flex is so short.  Some of your pictures show an extension flex. Is that a custom piece or did you manage to buy it from somewhere?

**Comment by rwb27** [comment]
Also, is there an STL for the 45 degree holder for the raspberry pi somewhere?

**Comment by beniroquai** [comment]
Hey @rwb27 you are totally right. We tried to sneak in the DMD driver close to the display and indeed we had a second board, where we simply took the cable and extended the first one (worked surprisingly well). I'm not sure if these cables are for sale individually. I remember I checked it and found some somewhere. I think if you enter this strange number on the flatband cable in a naive google search you may find it. The 45° holder was some sort of an improvisation. It gets away the stress from the DMD back facet. @ranranking wasn't there another solution with just one cable too?

**Comment by beniroquai** [comment]
I found this image, but that's already fairly old and one of the very first prototypes:

![image](https://user-images.githubusercontent.com/4345528/140302738-ce212aa8-7032-40f7-b3fa-e57c47fb9519.png)

**Comment by ranranking** [comment]
Unfortunately i used two cables for the system, because the DMD chip and board will have a 90 degree angle and the cable they provided is really short. It might easily loosen contact from the DMD connector to the cable. Maybe get a longer cable is a better way to do it
![Cables](https://user-images.githubusercontent.com/52754557/140305161-bc6126df-364a-4004-a200-1c5f34e42f16.jpg)

**Comment by ranranking** [comment]
And you can find the STL file here https://github.com/openUC2/UC2_openSIM/blob/main/OLD/ASSEMBLY_CUBE_openSIM/30_CUBE_openSIM_DLP2000_Holder.stl

**Comment by jfr26** [comment]
Have you found these cables for sale separately?

Additionally, did you drill holes in the holder to screw in the DMD?

**Comment by ranranking** [comment]
The flex cable we didn't find a proper acess to buy them separately. That's why we connected two cables togther.

When you tear down the DMD from the EVM, it has two small screws which are used to mount the DMD board. We reused the screws and mount it onto the 3D printed part. On the part design, it already has 2 holes which are fit for mount the DMD board.

**Comment by beniroquai** [comment]
Don't worry too much about the missing cable. It will still work. We "just"
need to come up with a smarter way on mounting the Raspi + DMD Driver
board. Definitely doable.

Am Mo., 8. Nov. 2021 um 18:29 Uhr schrieb ranranking <
***@***.***>:

**Comment by rwb27** [comment]
@ranranking I didn't see any screw holes on the printed part, which seemed odd to me - I wonder if they might have been lost somehow?

We'll have a play with it in the lab tomorrow, hopefully we will figure out a mounting solution that's not too horrible!

**Comment by ranranking** [comment]
Hmm it is weird. When you check the preview of the stl file on GitHub, it shows the holes at least to me.
![image](https://user-images.githubusercontent.com/52754557/140925070-092f3af4-2d48-4afc-9935-ab7208c30360.png)
And it is like that when you mount the DMD board onto it.
![102c66c7efeb468d8c6df03ff18a087](https://user-images.githubusercontent.com/52754557/140925540-661ca774-30b3-423c-8050-c2671a19aa9c.jpg)
The holes are 1.5mm sized, maybe not printed there? Then you can drill a small hole for the screw. I think the screws are something like M2.

**Comment by rwb27** [comment]
The part I was looking at was the rectangular plate in the new integrated version of the SIM module (so the DMD is on a kinematic mount).  On closer inspection it did have the holes, they'd just closed up during printing.  I was able to open them up again with a 1.5mm drill.  The holes in the PCB are smaller than M2, but I found some very small self tapping screws that worked.

**Comment by rwb27** [comment]
For the record, our current solution is that we've got the DMD head mounted on the kinematic mount, and some custom holders based on the part pictured above supporting the DMD board.  The custom PCB is then plugged onto the DMD, and we've used a 40 pin GPIO extender between that and the Raspberry Pi, so the Pi sits flat on the bench.  This seems to work nicely, and the £3 GPIO extender was much easier to get hold of than the extender for the DMD ribbon cable.

The ribbon cable does foul the kinematic mount though - it works, but it's bent at a slightly alarming angle.  Did you have that problem too?

**Comment by beniroquai** [comment]
@ranranking I think the two photographs you are showing are originating from two different setups, or? The "kinematic" mirror attempt was the newer version if I'm not mistaking. Is this also part of the files in the github? 

@rwb27 the extension is a smart solution to get some space! Thanks! :) 
Also, I think we should summarize the parts that did not work out of the box in order to improve the documentation. Should we create a checklist somewhere? 

Thanks!

**Comment by ranranking** [comment]
@rwb27 Sorry, i was always confused about which version are you using. That's why i am sending randomly images of the two version. Its nice that you find the hole at the end. For the DMD cable, i must say it is very tricky. We used two DMD cables and were mounting the whole DMD board and Raspberry Pi to the cubes and SIM module in vertical direction. I am not sure if the part is in the Git, that time was thinking it's also not a idea solution.
![image](https://user-images.githubusercontent.com/52754557/143862385-769d9706-84a4-4a7f-910e-ba4ef626d1af.png)

**Comment by ranranking** [comment]
I uploaded the file to the Git as well, in case it is useful. The idea was pack the DMD board with the Raspberry Pi togther and mount them to the whole module. With two ribbon cables, it did not give a huge force to the cable nor the board.
https://github.com/openUC2/UC2_openSIM/blob/main/CAD/30_CUBE_openSIM_DMD_Raspi_holder.stl
