### ISSUE TITLE
I2C bus on the Pi

### ISSUE THREAD

**Issue by jfr26** [openUC2/UC2_openSIM#5]
The I2C bus on the Pi 4 is different from that on the Pi 3. Does this affect the interaction with the DMD board? Following the setup instructions as given on this Github does not work with a Pi 4 at the moment.

https://docs.microsoft.com/en-us/windows/iot-core/learn-about-hardware/pinmappings/pinmappingsrpi

https://www.etechnophiles.com/raspberry-pi-4-gpio-pinout-specifications-and-schematic/#:~:text=Raspberry%20Pi%204%20GPIO%20Pinout%20has%2040%20pins%3A,supports%20SPI%2C%20I2C%2C%20and%20UART%20serial%20communication%20protocols.

**Comment by jfr26** [comment]
I managed to get an image by using

i2cset -y "ffffffff00000002.i2c" 0x1b 0x0b 0x00 0x00 0x00 0x00 i
i2cset -y "ffffffff00000002.i2c" 0x1b 0x0c 0x00 0x00 0x00 0x1b i

instead.

**Comment by beniroquai** [comment]
Hey @jfr26, I already heard from your problems you were facing from @rwb27. "you see an image" means, it works?! :) 
Would you mind making a PR to add this to the docu? also if you have any notes, where you got stuck in the documentation, please blame me for improving it! I think it is not fully reviewed so that others can replicate it easily. 
Thanks! :)
